//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18047
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUDAFingerprinting.Common.ConvexHull.Test {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CUDAFingerprinting.Common.ConvexHull.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;4&lt;/X&gt;
        ///    &lt;Y&gt;6&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;5&lt;/X&gt;
        ///    &lt;Y&gt;5&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;8&lt;/X&gt;
        ///    &lt;Y&gt;9&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;7&lt;/X&gt;
        ///    &lt;Y&gt;1&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;3&lt;/X&gt;
        ///    &lt;Y&gt;5&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///&lt;/ArrayOfPoint&gt;.
        /// </summary>
        internal static string TestArray1 {
            get {
                return ResourceManager.GetString("TestArray1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;4&lt;/X&gt;
        ///    &lt;Y&gt;6&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;3&lt;/X&gt;
        ///    &lt;Y&gt;5&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;7&lt;/X&gt;
        ///    &lt;Y&gt;1&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;8&lt;/X&gt;
        ///    &lt;Y&gt;9&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///&lt;/ArrayOfPoint&gt;.
        /// </summary>
        internal static string TestArray1Result {
            get {
                return ResourceManager.GetString("TestArray1Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;1&lt;/X&gt;
        ///    &lt;Y&gt;3&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;2&lt;/X&gt;
        ///    &lt;Y&gt;9&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;8&lt;/X&gt;
        ///    &lt;Y&gt;6&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;8&lt;/X&gt;
        ///    &lt;Y&gt;4&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;10&lt;/X&gt;
        ///    &lt;Y&gt;6&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;12&lt;/X&gt;
        ///    &lt;Y&gt;5&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;5&lt;/X&gt;
        ///    &lt;Y&gt;4&lt;/Y&gt;
        ///  &lt;/Point [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TestArray2 {
            get {
                return ResourceManager.GetString("TestArray2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;1&lt;/X&gt;
        ///    &lt;Y&gt;3&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;5&lt;/X&gt;
        ///    &lt;Y&gt;2&lt;/Y&gt;
        ///  &lt;/Point&gt; 
        ///  &lt;Point&gt;
        ///    &lt;X&gt;10&lt;/X&gt;
        ///    &lt;Y&gt;2&lt;/Y&gt;
        ///  &lt;/Point&gt; 
        ///  &lt;Point&gt;
        ///    &lt;X&gt;12&lt;/X&gt;
        ///    &lt;Y&gt;5&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;8&lt;/X&gt;
        ///    &lt;Y&gt;11&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;2&lt;/X&gt;
        ///    &lt;Y&gt;11&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///&lt;/ArrayOfPoint&gt;.
        /// </summary>
        internal static string TestArray2Result {
            get {
                return ResourceManager.GetString("TestArray2Result", resourceCulture);
            }
        }
    }
}
